### PR TITLE
[VIT-5893] - Add experimental expo health connect support

### PR DESCRIPTION
**Pull request by maitham**
Experimental expo health connect support

### CODE REVIEW

**Comment by anhtuan219** [comment]
Hi, I like to use expo for React Native, and it's great that tryvital started supporting expo

I followed the guide to use tryvital with expo, but the downloaded package doesn't include any `app.plugin.js` file (although I found it in the repo) which for expo to treat tryvital as a config plugin
When I manually add the `app.plugin.js` files in the folder package in `node_modules`, I can prebuild it successfully
Here's the command that I'm using to install tryvital, is there any wrong cause the package installed doesn't include any `app.plugin.js` file?
```
npx expo install @tryvital/vital-core-react-native && npx expo install @tryvital/vital-health-react-native && npx expo install @tryvital/vital-devices-react-native
```

When trying to fix the config plugin error, I found this PR. When I bring the changes in this PR to local `app.plugin.js`, I get another error


I think the problem came from the parameter of the exported function. The parameter is the config object, not an object containing the config object, so I remove the curly braces and after that, I can prebuild successfully




Could you check this, I'm looking forward to that tryvital supporting expo soon, thanks for reading

**Review by andersio — APPROVED** [review]

**Comment by punter82** [comment]
I installed the latest tryvital version (4.3.2) which includes experimental expo, I also followed [the docs for expo](https://github.com/tryVital/vital-react-native?tab=readme-ov-file#expo-installation).
But when I prebuild the ios project, the installed packages aren't treated as config plugins by expo and the build fails. When I open packages in node_modules, I can't find any app.plugin.js files, which may be the reason expo doesn't treat vital as a config plugin.
Screenshot 2024-10-06 at 3 53 09 PM
Screenshot 2024-10-06 at 3 53 23 PM

Can someone please check this. Thanks

**Comment by evanheisler** [comment]
I was having the same problem trying to update past `~4.1.0`. I ended up copying the `app.plugin.js` files from the `core` and `health` packages in this repo into my local `node_modules` folders and used `patch-package` to ensure the files were installed. 

It would seem somewhere early in v4, something broke in the publish process preventing these files from getting bundled.

**Comment by SamMcDuffie** [comment]
We are also seeing this issue on version 5.0.0

**Pull request merged**
